services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - rede-controlflux
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  mongo:
    image: mongo:4.2.18
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    networks:
      - rede-controlflux
    restart: always
    command: ["mongod", "--bind_ip", "0.0.0.0"]
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      - rede-controlflux
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
  node-red:
    image: nodered/node-red:4.0.2-22
    container_name: app
    ports:
      - 1880:1880
    environment:
      - MONGODB=mongo
    volumes:
      - ./node-red/data:/data
    networks:
      - rede-controlflux
    restart: always
volumes:
  mongo-volume:
networks:
  rede-controlflux:
    driver: bridge