version: '3'

services:
  nodered:
    build: .
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data/node-red
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  node_red_data:
  mysql_data:
